global:
  scrape_interval: 5s
  evaluation_interval: 1m

rule_files:
  - "instance-down_alert.yml"
  - "recruitment-portal-rule.yml"
# Alertmanager configuration

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['194.242.56.187:9093']

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['194.242.56.187:9090']

#  - job_name: cadvisor
#    scrape_interval: 5s
#    static_configs:
#    - targets: ['localhost:8081']

  - job_name: 'docker'
    scrape_interval: 10s
    static_configs:
      - targets: ['144.91.79.237:9323']

  - job_name: 'node'
    scrape_interval: 10s
    static_configs:
    - targets: ['144.91.79.237:9100']

  - job_name: 'container_exporter'
    scrape_interval: 1m
    scrape_timeout: 50s
    static_configs:
      - targets: ['144.91.79.237:9104']